### ISSUE TITLE
Doc inconsistency

### ISSUE THREAD

**Issue by jmccartin** [tylerni7/missile-tid#21]
A few issues across several files:

* [CONTRIBUTING.rst](https://github.com/tylerni7/missile-tid/blob/main/CONTRIBUTING.rst):
  * Does not mention checks outside of flake8 (no mypy, black, etc). 
  * Running tests (tox) conflicts with that in the Github actions. Also references to travis-ci are out of date. 
  * No mention of how to build documentation under `docs/`.
* [README.md](https://github.com/tylerni7/missile-tid/blob/main/README.md):
  * `Contributing` section should point to separate file
  * Status badges pointing to Github actions?
* [README.rst](https://github.com/tylerni7/missile-tid/blob/main/README.rst):
  * File seems to be out of date and conflicts with [README.md](https://github.com/tylerni7/missile-tid/blob/main/README.md) - remove?

More generally, there's some inconsistency on the recommended version of Python. There's not a whole lot of difference between the two, but the workflow actions build for 3.8 and 3.9, while [pyproject.toml](https://github.com/tylerni7/missile-tid/blob/main/pyproject.toml) only checks for 3.8. Slightly related, Python 3.10's pattern matching syntax is amazing and 3.11 has major performance increases across the board, so perhaps these base versions could be bumped (unless you need to keep back for compatibility reasons).

**Comment by tylerni7** [comment]
Sorry I've been bad about responding on here.

I've not worked hard on compatibility, 3.8 or 3.9 are probably fine, I'm okay committing to one of those.
The features in 3.10 and 3.11 are awesome, but I'm a bit wary just since I think some distros are pretty behind. I think Ubuntu 20.04 (admittedly a bit old, but still supported) is on 3.8, for example. And 22.04 is still on 3.10, so idk about 3.11...
